scrape_configs:
  - job_name: 'mobius-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['mobius-api:8080']
        labels:
          env: 'prod'
          app: 'mobius-api'

  - job_name: 'mobius-ledger'
    metrics_path: /metrics
    static_configs:
      - targets: ['mobius-ledger:9090']
        labels:
          env: 'prod'
          app: 'mobius-ledger'

  - job_name: 'attestation'
    metrics_path: /metrics
    static_configs:
      - targets: ['attestation-svc:8081']
        labels:
          env: 'prod'
          app: 'attestation'
