version: "3.9"
services:
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana-civic
    ports:
      - "3001:3000"
    environment:
      GF_INSTALL_PLUGINS: "marcusolsson-json-datasource"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
